### ISSUE TITLE
Grid card component

### ISSUE THREAD

**Issue by stevenabreu7** [techclubjacobs/app#28]
Finish the component in `src/components/GridCard.tsx` according to what we discussed. You are free to use libraries, open-source react components or design components. You don't have to copy the mockup design 1:1, feel free to be creative. 

You can mock all data (mock image, mock name, etc).

Make sure to highlight the card in some way when you hover over it.

**Comment by lorenzorota** [comment]
Please check if this suffices as the GridCard backbone
